# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SQL-Routine-SQLParser
version:      0.01
version_from: lib/SQL/Routine/SQLParser.pm
installdirs:  site
requires:
    Locale::KeyedText:             1.05
    SQL::Routine:                  0.65
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
